# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official

# Non-transitive R classes
android.nonTransitiveRClass=true

# Proxy for downloads
systemProp.http.proxyHost=<YOUR_PROXY_IP>
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=<YOUR_PROXY_IP>
systemProp.https.proxyPort=7890
